project_name: go-cve-search
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
brews:
  - github:
      owner: s-index
      name: homebrew-go-cve-search
    folder: Formula
    homepage: https://github.com/s-index/go-cve-search
    description: lightweight tool to search CVE (Common Vulnerabilities and Exposures)
    test: |
      system "#{bin}/goreleaser -v"
builds:
  - main: .
    binary: go-cve-search
    goos:
      - windows
      - darwin
      - linux
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: macOS
      linux: linux
      windows: windows
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
