version: 2.1
executors:
  default:
    docker:
      - image: circleci/golang:1.13.3
    working_directory: /go/src/github.com/s-index/go-cve-search
    environment:
      - GO111MODULE: "on"

jobs:
  test:
    executor:
      name: default
    steps:
    - checkout
    - run: go get github.com/s-index/go-cve-search
    - run: go test -v ./...

workflows:
  build-and-test:
    jobs:
      - test